---
# tasks file for docker

- name: install OS dependencies
  apt:
    name: "{{ debian_dependencies }}"
    state: present
  tags: install

- name: add GPG signing key
  become: true
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
    validate_certs: true
  tags: install

- name: add official repository
  become: true
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  register: docker_repo
  tags: install

- name: udpate apt cache
  become: true
  when: docker_repo.changed
  apt:
    update_cache: true
  tags: install

- name: establish dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_dependencies }}"
  tags: install

- name: ensure the docker service is running and enabled
  become: true
  service:
    name: docker
    state: started
    enabled: true
  tags:
    - install
    - configure
