---
# tasks file for postgresql
# configure postgresql and superuser

- name: network access | configure listening address to public
  lineinfile:
    path: /etc/postgresql/{{postgres_version}}/main/postgresql.conf
    line: listen_addresses = '*'
    insertafter: EOF
    state: present
  register: config_check
  tags: configure

- name: super user | configure password for postgres superuser
  become: true
  become_user: "{{ postgres_super_user }}"
  postgresql_user:
    name: "{{ postgres_super_user }}"
    password: "{{ postgres_super_password }}"
    state: present
  tags: configure

- name: timescaledb | configure shared preload libraries
  lineinfile:
    path: /etc/postgresql/{{postgres_version}}/main/postgresql.conf
    line: shared_preload_libraries = 'timescaledb'
    insertafter: EOF
    state: present
  register: config_check
  tags: configure

- name: restart PostgreSQL service after configuration
  become: true
  service:
    name: postgresql
    state: restarted
  when: config_check.changed
  tags: configure
