---
# tasks file for postgresql
# add db, users to db and pg_hba.conf

- name: admin users | configure password for postgres superuser
  become: true
  become_user: "{{ postgres_database_user }}"
  postgresql_user:
    name: "{{ postgres_database_user }}"
    password: "{{ postgres_database_password }}"
    state: present
  tags: configure

- name: database | ensure database "{{ postgres_database_name }}" exists
  become: true
  become_user: "{{ postgres_database_user }}"
  postgresql_db:
    name: "{{ postgres_database_name }}"
    owner: "{{ postgres_database_user }}"
    state: present
  tags: configure

- name: admin users | add admin user
  become: true
  become_user: "{{ postgres_database_user }}"
  postgresql_user:
    db: "{{ postgres_database_name }}"
    name: "{{ postgres_admin_user }}"
    password: "{{ postgres_admin_password }}"
    priv: "ALL"
    role_attr_flags: SUPERUSER,CREATEROLE,CREATEDB,INHERIT,LOGIN,REPLICATION,BYPASSRLS
    state: present
  tags: configure

- name: admin users | grant network access to admin user
  postgresql_pg_hba:
    dest: /etc/postgresql/{{ postgres_version }}/main/pg_hba.conf
    contype: host
    users: "{{ postgres_admin_user }}"
    source: samehost
    databases: "{{ postgres_database_name }}"
    method: scram-sha-256
    create: true
  tags: configure

- name: databases | set owner to admin user
  become: true
  become_user: "{{ postgres_database_user }}"
  postgresql_owner:
    db: "{{ postgres_database_name }}"
    new_owner: "{{ postgres_admin_user }}"
    obj_name: "{{ postgres_database_name }}"
    obj_type: database
  tags: configure

- name: users | create users
  become: true
  become_user: "{{ postgres_database_user }}"
  postgresql_user:
    db: "{{ postgres_database_name }}"
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    priv: "CONNECT"
    state: present
  loop: "{{ postgres_users }}"
  loop_control:
    label: "{{ item.username }}"
  no_log: true # do not output passwords to log
  tags: configure

- name: users | grant network access to users
  postgresql_pg_hba:
    dest: /etc/postgresql/{{ postgres_version }}/main/pg_hba.conf
    contype: host
    users: "{{ postgres_users | map(attribute='username') | join(',') }}"
    source: all
    databases: "{{ postgres_database_name }}"
    method: scram-sha-256
    create: true
  tags: configure
