---
# tasks file for postgresql
# configure network access
# add db, users to db and pg_hba.conf

- name: network access | configure listening address to public
  lineinfile:
    path: /etc/postgresql/{{postgres_version}}/main/postgresql.conf
    line: listen_addresses = '*'
    insertafter: EOF
    state: present

- name: super user | configure password for postgres superuser
  become: true
  become_user: "{{ postgres_super_user }}"
  postgresql_user:
    name: "{{ postgres_super_user }}"
    password: "{{ postgres_super_password }}"
    state: present
  tags: configure
