global:
  telegram_api_url: 'https://api.telegram.org'
  slack_api_url_file: /etc/alertmanager/slack_api_url

templates:
- templates/mitwelten_slack.tmpl

route:
  receiver: root
  group_by: [alertname]
  routes:
  - receiver: teams
    continue: true
    repeat_interval: 30m
    matchers:
    - severity = "critical"
  - receiver: teams
    continue: true
    repeat_interval: 6h
    matchers:
    - severity = "error"
  - receiver: teams
    continue: true
    repeat_interval: 12h
    matchers:
    - severity = "warning"
  - receiver: teams
    continue: true
    repeat_interval: 24h
    matchers:
    - severity = "info"

receivers:
- name: root
- name: teams
  webhook_configs:
  - url: "http://prom2teams:8089"
    send_resolved: true

# Inhibition rules allow to mute a set of alerts given that another alert is
# firing.
# We use this to mute any warning-level notifications if the same alert is
# already critical.
inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: # Apply inhibition if the alertname is the same.
      - alertname
      - cluster
      - service
