version: '3.3'

services:
  traefik:
    image: "traefik:v2.7"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.mqtts.address=:8883"
      - "--certificatesresolvers.ssl.acme.tlschallenge=true"
      - "--certificatesresolvers.ssl.acme.email=mitwelten.technik@fhnw.ch"
      - "--certificatesresolvers.ssl.acme.storage=/letsencrypt/acme.json"

    ports:
      - "80:80"
      - "443:443"
    #  - "8883:8883"

    volumes:
      - "/etc/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    #labels:
    #  - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
    #  - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
    restart: always

  viz-api:
    image: mitwelten-viz:0.1
    container_name: "mitwelten-viz-api"
    volumes:
      - "/opt/mitwelten-db-backend/services/viz:/app"
      - "/opt/mitwelten-db-backend/credentials.py:/app/credentials.py" 
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.viz_api.loadbalancer.server.port=80"

      # for https
      - "traefik.http.routers.viz_api_insecure.rule=Host(`data.mitwelten.org`)&&PathPrefix(`/viz`)"
      - "traefik.http.routers.viz_api_insecure.entrypoints=http"
      # redirect to https
      - "traefik.http.middlewares.viz-api-https.redirectscheme.scheme=https"
      - "traefik.http.routers.viz_api_insecure.middlewares=viz-api-https"
      
      # for https
      - "traefik.http.routers.viz_api.rule=Host(`data.mitwelten.org`)&&PathPrefix(`/viz`)"
      - "traefik.http.routers.viz_api.entrypoints=https"
      - "traefik.http.routers.viz_api.tls.certresolver=ssl"

      # chain middlewares
      - "traefik.http.middlewares.viz_api.chain.middlewares=viz-api-stripprefix,viz-api-basic-auth"

      # strip prefix /viz/v1
      - "traefik.http.middlewares.viz-api-stripprefix.stripprefix.prefixes=/viz/v1"

      # basic auth
      - "traefik.http.middlewares.viz-api-basic-auth.basicauth.users=${VIZ_API_BASIC_AUTH_USER_PW}"

     # - "traefik.http.routers.viz_api.middlewares=viz-api-stripprefix"
     # - "traefik.http.routers.viz_api.middlewares=viz-api-basic-auth"



    restart: always

