global:
  scrape_interval:     10s # Set the scrape interval to every 10 seconds. Default is every 1 minute.
  scrape_timeout:      10s # The default is every 10 seconds.
  evaluation_interval: 10s # Evaluate rules every 10 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 172.17.0.1:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
- alert.rules.yml
- alerts/*.yml

scrape_configs:

- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

- job_name: picam-capture
  scheme: https
  relabel_configs:
  - source_labels: [__address__]
    regex: '.+(ap-\d{4}-\d{4})-.+'
    target_label: instance
  file_sd_configs:
  - files:
    - /etc/prometheus/sd/mitwelten_capture-nodes.json
    refresh_interval: 5m

- job_name: node_proxy
  proxy_url: http://pushprox:8082/
  scheme: http
  static_configs:
    - targets: ['ba14ns21425.adm.ds.fhnw.ch:9100']
  relabel_configs:
    - source_labels: [__address__]
      target_label: instance
    - target_label: job
      replacement: node

- job_name: node_local
  static_configs:
    - targets: ['v000744.fhnw.ch:9100']
  relabel_configs:
    - source_labels: [__address__]
      target_label: instance
    - target_label: job
      replacement: node
